/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package handson.commons.domain.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum PaymentStatus { 
  AUTHORIZED, IN_ANALYSIS, DENIED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PaymentStatus\",\"namespace\":\"handson.commons.domain.avro\",\"symbols\":[\"AUTHORIZED\",\"IN_ANALYSIS\",\"DENIED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
