/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package handson.commons.domain.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ProductType { 
  SUBSCRIPTION, INVOICE, ECOMMERCE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ProductType\",\"namespace\":\"handson.commons.domain.avro\",\"symbols\":[\"SUBSCRIPTION\",\"INVOICE\",\"ECOMMERCE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
